### ISSUE TITLE
Error occurs when running train_script.sh training GCN

### ISSUE THREAD

**Issue by K-Coconut** [idea-iitd/GCOMB#5]
Hi, firstly, thanks for your opening algorithm and code, which is amazing.  Something wrong occurs when I run the code and sorry I don't know how to fix it. 

tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[331500] = 69578 is not in [0, 69578)
	 [[node embedding_lookup_2 (defined at graphsage/models.py:300) ]]

------------------------------------------------

Entered in the Loop  =           == = == = ==
WARNING:tensorflow:From /gpfs1/home/zhicliang3/git/GCOMB/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervised_train.py:298: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

W0118 18:59:31.573591 23456246036288 deprecation_wrapper.py:119] From /gpfs1/home/zhicliang3/git/GCOMB/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervised_train.py:298: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

Trained Model Loading!
WARNING:tensorflow:From /home/zhicliang3/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0118 18:59:31.583878 23456246036288 deprecation.py:323] From /home/zhicliang3/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from KITE_supervisedTrainedModel_MC_marginal/model.ckpt
I0118 18:59:31.584534 23456246036288 saver.py:1280] Restoring parameters from KITE_supervisedTrainedModel_MC_marginal/model.ckpt
Trained Model Loaded!
Epoch: 0001
Traceback (most recent call last):
  File "/home/zhicliang3/anaconda3/envs/py27/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/zhicliang3/anaconda3/envs/py27/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/gpfs1/home/zhicliang3/git/GCOMB/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervised_train.py", line 387, in <module>
    tf.app.run()
  File "/home/zhicliang3/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/zhicliang3/anaconda3/envs/py27/lib/python2.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/zhicliang3/anaconda3/envs/py27/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/gpfs1/home/zhicliang3/git/GCOMB/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervised_train.py", line 384, in main
    train(train_data)
  File "/gpfs1/home/zhicliang3/git/GCOMB/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master/graphsage/supervised_train.py", line 317, in train
    outs = sess.run([merged, model.opt_op, model.loss, model.preds], feed_dict=feed_dict)
  File "/home/zhicliang3/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/zhicliang3/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zhicliang3/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/zhicliang3/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[331500] = 69578 is not in [0, 69578)
	 [[node embedding_lookup_2 (defined at graphsage/models.py:300) ]]**

Errors may have originated from an input operation.
Input Source operations connected to node embedding_lookup_2:
 Variable/read (defined at graphsage/supervised_models.py:60)
 Reshape_1 (defined at graphsage/models.py:274)

**Comment by sahilm1992** [comment]
Hi,
We will get back to you shortly on this.

**Comment by K-Coconut** [comment]
> Hi,
> We will get back to you shortly on this.

Thanks! Sorry for my first comment, I miss something important. I ran the code by "python train_multiple.py", which is under "GCOMB/MaxCover-20200616T101530Z-001/MaxCover/GraphSAGE-master".

Thanks in advance.

**Comment by sahilm1992** [comment]
Till that time, 
could you share the following details:
1.Libraries used by you with the version.
2.The commands you ran.
3. Operating System

**Comment by sahilm1992** [comment]
Thanks for the information. I will check and get back to you.

**Comment by K-Coconut** [comment]
Actually I ran the program on Mac without gpu and Linux with GPU, **and the same error occurred.**

## Mac 10.15.7 

Branch: Master

1. Libraries are consistent with the ones from requirements_2.7.txt from branch Master.
> tensorboard          1.8.0
> tensorflow           1.8.0
> tensorflow-estimator 2.1.0
....

2. Without gpu

## Linux 
Something weird occurs that I can't import tensorflow with version at 1.18, so I use the 1.14 one.

1. Other libraries are consistent with the ones from requirements_2.7.txt from branch Master.
> tensorflow           1.14.0
> tensorflow-estimator 1.14.0
> tensorflow-gpu       1.13.1
...
2. operating system
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterprise
Description:	Red Hat Enterprise Linux release 8.1 (Ootpa)
Release:	8.1
Codename:	Ootpa

**Comment by sahilm1992** [comment]
Sure. Thanks. I will get back to you shortly.

**Comment by GoingMyWay** [comment]
The same issue, appreciate if you can help.

**Comment by sahilm1992** [comment]
Sure, we will update you on this soon. Need to verify the issue on our end.

**Comment by K-Coconut** [comment]
Hi, sorry but may I ask how is it going? By the way, I also noticed that some codes seem to be the old version ones and can't run properly some days ago. Is there any newer version?  Thanks in advance.

**Comment by sahilm1992** [comment]
Hi, 
I am having difficulty reproducing the issue at my end. I am still working on it. Will get back as soon as possible. There is no newer version.

**Comment by K-Coconut** [comment]
Thanks for your help ~

**Comment by Haipeng-Chen** [comment]
I had the same issue. I figured out that this is due to the construct_adj() function in mini_batch.py, where nodes who don’t have neighbors are assigned ‘fake’ neighbors with id=len(G). This makes the indices of the ‘fake’ neighbors out of range for the model.features. I feel this actually has nothing to do with the system but just a missing pre-processing step to eliminate the nodes with no neighbors (i.e., isolated nodes). Could the authors confirm whether this is true? Thanks!

**Comment by sahilm1992** [comment]
Thanks for the detailed report.

There is probably some networkx version issue playing a role.
I am checking on my side. Will revert back to you.

-
Sahil Manchanda
www.cse.iitd.ac.in/~sahilm

**Comment by sahilm1992** [comment]
Could you please try it now.
Please do a fresh git pull. 
use the new requirements file present in https://github.com/idea-iitd/GCOMB

https://github.com/idea-iitd/GCOMB/blob/master/requirements_python2.7.txt
https://github.com/idea-iitd/GCOMB/blob/master/requirements_python3.txt


Just to be sure, I have put all packages that I had in my environment.

**Comment by K-Coconut** [comment]
Thanks for your help @sahilm1992 @Haipeng-Chen 
I will take it a try later.

**Comment by sahilm1992** [comment]
There is another slight issue that can happen.
I will be uploading a fixed version shortly.

**Comment by Haipeng-Chen** [comment]
Thank you! @sahilm1992 Appreciate your help.

**Comment by sahilm1992** [comment]
Kindly try now after fresh pull with updated requirements  file for both python 2 and python 3.

**Comment by K-Coconut** [comment]
Hi, appreciate your help! Inspired by @Haipeng-Chen , I solve my problem. 

For my case, MaxCover problem, when executing supervised_train, line 164 initializing NodeMinibatchIterator,  initialize an adj matrix as id=len(G), then in the loop for those nodes who don't have neighbors (isolated nodes) and the ones marked as 'test', 'val' will not change the initial adj value of theirs, line 281, line 287 in minibatch.py.
For this reason, the problem "out of range for the model.features" happens.

More details, As for Kite graph (I haven't tested on other graphs yet ), there not exists isolated nodes that don't have neighbors, so in this case, it is not the fault of preprocessing part.
\>\>\>  len([i for i in G.nodes() if not G.neighbors(i)])
0

it's due to without removing test/val nodes from train nodes.
\>\>\> [i for i in self.train_nodes if G.node[i]['test']]
695


--- My Solution ---
I think test_nodes is not assigned properly in line 216 (minibatch.py).
it's empty here, maybe it should be modified into G.node[n]['test']?
\>\>\> len([n for n in self.G.nodes() if self.G.node[n]['val']])
0

(Also, val_nodes should take G.node[n]['val'] ones. But since G.node[n]['val'] is empty in Kite graph, 
so it's OK to take first 1000 node in train_nodes here, but same problem will occur for those graphs whose G.node[n]['val'] is not empty)

modifiy line 216 into : self.test_nodes=[n for n in self.G.nodes() if self.G.node[n]['test']]
and unannotated line 223-224, we have the train_nodes whose adj values without len(G) which cause the out of index problem.
\>\>\> len(G) in self.adj[self.train_nodes]
False

Then, some neighbors of train nodes are still test nodes whose adj value are len(G). When sampling neighbors, it has a certain probability that the test nodes are selected and the problem out of index happens again.
\>\>\> len([neib for i in self.train_nodes for neib in G.neighbors(i) if len(G) in self.adj[neib]])
826

remove them:
self.train_nodes = [n for n in self.train_nodes if not set(self.G.neighbors(n)).intersection(self.no_train_nodes_set)]

Finally, we have the train_nodes and their neighbors without mixing up test nodes and val nodes, and the problem is solved. In all, the problem is just due to the `fake` neighbors value not assigned properly.  
Could you please confirm whether it is true?  I will submit my code if needed.


--- Some other questions ---
However, I suppose that there must be some reasons that line 223-224 annotated, but I think it is important to remove test and val nodes whose neighbors values are assigned as len(G) in train nodes. So are there any key points here?
By the way, for the comment: # don't train on nodes that only have edges to test set
it seems that code in line 226 can't achieve the purpose and why we should take the nodes from [0:int(len(G) / 2)] only?

**Comment by sahilm1992** [comment]
A lot of code from GraphSage node classifiction task was adopted here actually and doesn't have much relevance in this task.  So the keywords such as train/test/val in Graphsage code might not  have the same meaning as in Node classification task.

**Comment by sahilm1992** [comment]
I will look into your comments in detail though.

**Comment by sahilm1992** [comment]
The training is running perfectly on my system though with the current version of code.

**Comment by K-Coconut** [comment]
That's pretty weird, maybe I missed some steps before training.
I just simply run the python script MaxCover/GraphSAGE-master/train_multiple.py. Is there any preprocessing script I should run first?

**Comment by sahilm1992** [comment]
Have you installed the latest requirements file present on homepage?

Check the readme inside max cover folder.

**Comment by sahilm1992** [comment]
I am planning to release a docker version, but it might take some time.

**Comment by K-Coconut** [comment]
Yeah, I have created a new conda environment for python 3.5 and install all the requirements specified in the requirements file but the problem occurs all the same. Appreciate your patience.

**Comment by sahilm1992** [comment]
Have you also done it for python 2.7?

**Comment by sahilm1992** [comment]
Also can you use the train_script.sh instead of running commands manually. As mentioned in Readme outside, we need to use 2 python versions to run the project.

**Comment by K-Coconut** [comment]
I have also done that for python2.7. To make sure, I just do that again.
I used the train_script.sh just now. And the problem occurs no matter python2 or python3 running train_multiple.py

**Comment by K-Coconut** [comment]
The program complaints about the out of index problem, I think is not about the system problem. But maybe a docker environment can help.

**Comment by sahilm1992** [comment]
I will re-check on a fresh machine. Will let you know.

**Comment by sahilm1992** [comment]
After doing fresh git pull with the libraries provided, its running on my machine
Ubuntu 16.04.5 LTS
using cuda10.0


The logs are below


MaxCover$ ./train_script.sh                                    ('Training on Multiple Graphs =========== ', 0)
sh ./example_supervised.sh ./real_data/large_kite/train/_bp
--train_prefix ./real_data/large_kite/train/_bp --model graphsage_meanpool --sigmoid
Loading training data..
 num nodes  69578
 num nodes  69578
Done loading training data..
1000 34789
prefix ./real_data/large_kite/train/_bp
shape feature before  (69578, 1)
shape feature after keeping one feature (69578, 1)
WARNING:tensorflow:From /home/akash/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.p                                y:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From graphsage/layers.py:107: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob                                 is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/akash/.local/lib/python2.7/site-packages/tensorflow/python/ops/losses/losses_impl.py:                                667: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/akash/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_i                                nt32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2021-02-24 17:42:11.825787: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions tha                                t this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-02-24 17:42:12.024698: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5731800 executing compu                                tations on platform CUDA. Devices:
2021-02-24 17:42:12.024747: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce                                 GTX 1080 Ti, Compute Capability 6.1
2021-02-24 17:42:12.051577: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600000000 Hz
2021-02-24 17:42:12.056764: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x58d8200 executing compu                                tations on platform Host. Devices:
2021-02-24 17:42:12.056788: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefin                                ed>, <undefined>
2021-02-24 17:42:12.056935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties                                :
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:1b:00.0
totalMemory: 10.92GiB freeMemory: 10.05GiB
2021-02-24 17:42:12.056952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2021-02-24 17:42:12.058229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecu                                tor with strength 1 edge matrix:
2021-02-24 17:42:12.058242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2021-02-24 17:42:12.058248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2021-02-24 17:42:12.058324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/jo                                b:localhost/replica:0/task:0/device:GPU:0 with 9777 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 T                                i, pci bus id: 0000:1b:00.0, compute capability: 6.1)
[SAGEInfo(layer_name='node', neigh_sampler=<graphsage.neigh_samplers.UniformNeighborSampler object at 0x7f0d97545bd                                0>, num_samples=15, output_dim=128), SAGEInfo(layer_name='node', neigh_sampler=<graphsage.neigh_samplers.UniformNei                                ghborSampler object at 0x7f0d97545bd0>, num_samples=25, output_dim=128)]
Entered in the Loop  =           == = == = ==
Trained Model Loading!
WARNING:tensorflow:From /home/akash/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1266: ch                                eckpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a futu                                re version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Trained Model Loaded!
Epoch: 0001
2021-02-24 17:42:13.392567: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcub                                las.so.10.0 locally
Iter: 0000 train_loss= 0.00350781

**Comment by sahilm1992** [comment]
are you running on gpu or without gpu?
Can you check the gpu ids in the following files:

MaxCover/GraphSAGE-master/graphsage/supervisedPredict.py
MaxCover/GraphSAGE-master/graphsage/supervised_train.py
MaxCover/nn.py
MaxCover/get_output.py


Please check for keywords: CUDA_VISIBLE_DEVICES / gpu etc.

**Comment by sahilm1992** [comment]
FYI, the code works only with gpu

**Comment by K-Coconut** [comment]
Thanks for your advice, I ran the code on mac without gpu. I will check that on a gpu machine later. Will come back later.

**Comment by sahilm1992** [comment]
Make sure to set the gpu ids correctly in the above mentioned files.
Ill put that in readme. thanks

**Comment by K-Coconut** [comment]
Could you please also prepare a docker environment later? Thanks in advance

**Comment by sahilm1992** [comment]
Sure. But would take time

**Comment by zxpekko** [comment]
Hello, I have another problem.There are no node or neighbors in _bp-G.json. Why are these objects used in minibatch, and the code here also reports an error. The reason for the error is that there are no such objects. How can I solve this problem?Thank you very much.

**Comment by sahilm1992** [comment]
linked to https://github.com/idea-iitd/GCOMB/issues/18
